<?php
declare(strict_types=1);

namespace NeoFramework\Core\Config;

/**
 * Loads application configuration once, or from the atomically generated cache.
 * Configuration files are deliberately PHP arrays: they are evaluated only at
 * bootstrap/config:cache time, never by a cached production application.
 */
final class ConfigRepository implements ConfigRepositoryInterface
{
    /** @var array<string,mixed> */
    private array $items;

    /** @param array<string,mixed>|null $items */
    public function __construct(private readonly string $root, ?array $items = null, bool $preferCache = true)
    {
        $this->items = $items ?? ($preferCache && is_file($this->cacheFile())
            ? self::readCache($this->cacheFile())
            : $this->loadFiles());
    }

    public static function fromRoot(?string $root = null, bool $preferCache = true): self
    {
        return new self($root ?? \NeoFramework\Core\Support\ProjectRoot::path(), preferCache: $preferCache);
    }

    public function get(string $key, mixed $default = null): mixed
    {
        self::assertKey($key);
        $value = $this->items;

        foreach (explode('.', $key) as $part) {
            if (!is_array($value) || !array_key_exists($part, $value)) {
                return $default;
            }
            $value = $value[$part];
        }

        return $value;
    }

    public function require(string $key): mixed
    {
        $missing = new \stdClass();
        $value = $this->get($key, $missing);

        if ($value === $missing) {
            throw new ConfigurationException("Missing required configuration key '{$key}'.");
        }

        return $value;
    }

    /** @return array<string,mixed> */
    public function all(): array
    {
        return $this->items;
    }

    /** @return array<string,mixed> */
    public function fresh(): array
    {
        return $this->loadFiles();
    }

    public function cache(): void
    {
        $items = $this->loadFiles();
        ConfigValidator::validate($items);
        self::assertCacheable($items);
        $file = $this->cacheFile();
        $dir = dirname($file);

        if (!is_dir($dir) && !mkdir($dir, 0775, true) && !is_dir($dir)) {
            throw new ConfigurationException("Unable to create configuration cache directory '{$dir}'.");
        }

        $tmp = $file . '.' . bin2hex(random_bytes(6)) . '.tmp';
        $php = "<?php\n\ndeclare(strict_types=1);\n\n// Generated by 'neof config:cache'. Do not edit.\nreturn " . var_export($items, true) . ";\n";
        if (file_put_contents($tmp, $php, LOCK_EX) === false || !rename($tmp, $file)) {
            @unlink($tmp);
            throw new ConfigurationException("Unable to write configuration cache '{$file}'.");
        }
        $this->items = $items;
    }

    public function clearCache(): bool
    {
        $file = $this->cacheFile();
        return !is_file($file) || unlink($file);
    }

    public function cacheFile(): string
    {
        return rtrim($this->root, '/\\') . DIRECTORY_SEPARATOR . 'Cache' . DIRECTORY_SEPARATOR . 'config.php';
    }

    /** @return array<string,mixed> */
    private function loadFiles(): array
    {
        $directory = rtrim($this->root, '/\\') . DIRECTORY_SEPARATOR . 'Config';
        if (!is_dir($directory)) {
            return [];
        }

        $files = glob($directory . DIRECTORY_SEPARATOR . '*.php') ?: [];
        sort($files, SORT_STRING);
        $config = Defaults::all();

        foreach ($files as $file) {
            if (basename($file) === 'schema.php') {
                continue;
            }
            $value = include $file;
            if (!is_array($value)) {
                throw new ConfigurationException("Configuration file '{$file}' must return an array.");
            }
            $name = preg_replace('/(?:\.config)?\.php$/', '', basename($file));
            if (!is_string($name) || $name === '') {
                throw new ConfigurationException("Invalid configuration filename '{$file}'.");
            }
            $config[$name] = isset($config[$name]) && is_array($config[$name])
                ? array_replace_recursive($config[$name], $value)
                : $value;
        }

        return $config;
    }

    /** @return array<string,mixed> */
    private static function readCache(string $file): array
    {
        $items = include $file;
        if (!is_array($items)) {
            throw new ConfigurationException("Configuration cache '{$file}' is invalid. Run 'neof config:clear'.");
        }
        return $items;
    }

    private static function assertKey(string $key): void
    {
        if ($key === '' || preg_match('/(^\.|\.$|\.\.)/', $key)) {
            throw new ConfigurationException("Invalid configuration key '{$key}'.");
        }
    }

    private static function assertCacheable(mixed $value, string $path = 'root'): void
    {
        if ($value === null || is_scalar($value)) {
            return;
        }
        if (!is_array($value)) {
            throw new ConfigurationException("Configuration value '{$path}' cannot be cached; use scalars and arrays only.");
        }
        foreach ($value as $key => $item) {
            self::assertCacheable($item, $path . '.' . (string) $key);
        }
    }
}
